- name: Change user password
  hosts: raspi
  become: true
  
  vars_prompt:
    - name: username
      prompt: "Username"
      private: false
    - name: password
      prompt: "Password"
  
  tasks:
  - name: Change linux user password
    ansible.builtin.user:
      name: "{{ username }}"
      state: present
      password: "{{ password | password_hash('sha512') }}"
  
  - name: Change Samba password
    ansible.builtin.shell:
      "set -o pipefail && printf '%s\n%s\n' '{{ password }}' '{{ password }}' | smbpasswd -s -a {{ username }}"
  
  - name: Restart SMB
    ansible.builtin.service:
      name: smbd
      state: restarted