- name: Create linux users
  hosts: raspi
  become: true

  vars_files:
    - ../../vars.yml

  tasks:
    - name: Validate usernames
      ansible.builtin.assert:
        that: item.name is match("^[a-zA-Z0-9_]+$")
        msg: "Invalid username: {{ item.name }}"
      loop: "{{ users }}"

    - name: Prevent "shared" username
      ansible.builtin.assert:
        that: item.name != "shared"
        msg: 'The username "shared" is not allowed.'
      loop: "{{ users }}"

    - name: Create "users" group
      ansible.builtin.group:
        name: users

    - name: Create linux users
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ default_user_password | password_hash }}"
        update_password: on_create
        groups: users
        append: true
      register: user_creation
      loop: "{{ users }}"
