- name: Setup samba
  hosts: raspi
  become: true

  vars_files:
    - ../../vars.yml

  vars:
    samba_shared_folder: "{{ data_root }}/shared"

  handlers:
    - name: Restart SMB
      ansible.builtin.service:
        name: smbd
        state: restarted

  tasks:
    - name: Create data folder
      ansible.builtin.file:
        path: "{{ data_root }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Create shared folder
      ansible.builtin.file:
        path: "{{ samba_shared_folder }}"
        state: directory
        owner: root
        group: users
        mode: "2775"

    - name: Create user folders
      ansible.builtin.file:
        path: "{{ data_root }}/{{ item.name }}"
        state: directory
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
        mode: "700"
      loop: "{{ users }}"

    - name: Install Samba
      ansible.builtin.apt:
        name: samba

    - name: Copy smb config to /etc/samba/smb.conf
      ansible.builtin.template:
        src: 02_smb/smb.conf.j2
        dest: /etc/samba/smb.conf
        mode: "644"
      notify: Restart SMB

    - name: Set Samba password
      ansible.builtin.shell: "set -o pipefail && printf '%s\n%s\n' '{{ default_user_password }}' '{{ default_user_password }}' | smbpasswd -s -a {{ item.name }}"
      loop: "{{ users }}"
      loop_control:
        index_var: user_index
      when: user_creation.results[user_index].changed
      notify: Restart SMB

    - name: Start and enable Samba
      ansible.builtin.service:
        name: smbd
        enabled: true
        state: started

    - name: Install wsdd2
      ansible.builtin.apt:
        name: wsdd2
        state: present

    - name: Start and enable wsdd2
      ansible.builtin.service:
        name: wsdd2
        state: started
        enabled: true
