- ansible.builtin.import_playbook: 00_linux_users.yml
- ansible.builtin.import_playbook: 01_cockpit.yml
- ansible.builtin.import_playbook: 02_smb.yml
- ansible.builtin.import_playbook: 03_docker.yml
- ansible.builtin.import_playbook: 04_openspeedtest.yml
- ansible.builtin.import_playbook: 05_pihole.yml
- ansible.builtin.import_playbook: 06_tailscale.yml
- ansible.builtin.import_playbook: 07_immich.yml
- ansible.builtin.import_playbook: 08_motioneye.yml
- ansible.builtin.import_playbook: 99_homer.yml
